### ISSUE TITLE
报错了？

### ISSUE THREAD

**Issue by 0xe1e** [Majjcom/BiliDownloader#1]
错误: <class 'json.decoder.JSONDecodeError'>, Expecting value: line 1 column 1 (char 0), <traceback object at 0x04F8A488>
Traceback (most recent call last):
  File "J:\Python\BiliAPI\windowMake\videoDownloaderWindow.py", line 850, in Main
  File "J:\Python\BiliAPI\windowMake\videoDownloaderWindow.py", line 764, in start_download_video
  File "J:\Python\BiliAPI\windowMake\videoDownloaderWindow.py", line 329, in videoDown
  File "C:\Users\Administrator\Downloads\bili\bin\lib\site-packages\bili_api\video.py", line 138, in get_video_online_count
    get: dict = utils.network.get_data(
  File "C:\Users\Administrator\Downloads\bili\bin\lib\site-packages\bili_api\utils\network.py", line 29, in get_data
    ret = json.loads(r.read())
  File "C:\Users\Administrator\Downloads\bili\bin\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\Downloads\bili\bin\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\Downloads\bili\bin\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Majjcom** [comment]
大部分问题已修复
