### ISSUE TITLE
简介页面暂无评分时应用无法正常获取信息

### ISSUE THREAD

**Issue by Zack-Will** [Majjcom/BiliDownloader#4]
如题，md21103291在获取信息时会提示
未知错误
'rating'

Traceback (most recent call last):
  File "confirmwidget.py", line 83, in run
  File "confirmwidget.py", line 182, in load_data
KeyError: 'rating'

**Comment by Majjcom** [comment]
此问题已在1.0.5中得到修复，更新已推送
